import java.lang.Math;
import java.util.Scanner;
import java.util.Random;
import java.util.Arrays;

public class GuessingGame {
	// public static int[] ;

	public static void main(String[] args) {
		
		startGame();

	}

	// A method for generating random numbers between min and max
	public static int genRanInt(int min, int max) {
	    Random r = new Random();
	    return r.nextInt((max - min) + 1) + min;
	}
	
	// Generates random array by computer according to the user input length - defined as a method "genRanInt"
	public static int[] createString (int len) {
		// Generates random array by computer according to the user input length - defined as a method "genRanInt"
		int gen[]=new int[len];  
		for (int i = 0; i <= len-1; i++) {
			gen[i] = genRanInt(97,122); // z = 122 and a = 97
		}
		return(gen);
	}
	
	// A method to start the game. It calls createString and genRanInt
	public static void startGame() {
		
		// Initialize the Scanner object
				Scanner input = new Scanner(System.in);      
				System.out.print("Enter the String length: "); 
				int len = input.nextInt();				 
				
				// Generates random array by computer according to the user input length - defined as a method "genRanInt"
				int[] guess = createString(len);
				
				// Initialize an empty user array - this will be filled by user's true guesses step by step
				int u[]=new int[len];
				
				// Initialize the empty array (String) of user to show it to user 
				String us[] = new String[len];
				for (int i = 0; i <= len-1; i++)
					us[i] = "_ ";
				
				System.out.println("Start guessing the String:");
				int i = 1; // counter
				
				 
				
				
				// ***************************
				// Start getting user's inputs
				int check = 0;
				while (check == 0) {
						
					// Getting user's first input
					System.out.print("Guessing(round " + i + "): Choosing your character from a-z: ");
					String s = input.next();
						 
					char ch = s.charAt(0);		// Read the first character from the input string
					int chascii = (int) ch;	    // Returns the ASCII of a char z=122 a=97
						 
						// Check if the user has already selected this character
						 while (Arrays.asList(us).contains(s)) {
							System.out.println(s + " has been chosen before, try again.");
							System.out.print("Guessing(round " + i + "): Choosing your character from a-z: ");
							s = input.next();
							ch = s.charAt(0);	
							chascii = (int) ch;
							
						 }
						 
						// Check if the input has only one character 
						while (s.length() > 1) {
							System.out.println("You should not enter more than 1 character");
							System.out.print("Guessing(round " + i + "): Choosing your character from a-z: ");
							s = input.next();
							ch = s.charAt(0);	
							chascii = (int) ch;
						}
						
						// Check if the user input is in the range from a to z
						while (chascii > 122 || chascii < 97) {
							System.out.println("Your character should be in the range a to z.");
							System.out.print("Guessing(round " + i + "): Choosing your character from a-z: ");
							s = input.next();
							ch = s.charAt(0);	
							chascii = (int) ch;
							}
						 
						 // Check if the user input exists in the array generated by computer
						 for (int j = 0; j <= len-1; j++) {
								if (guess[j] == chascii) {
									u[j] = chascii;
									char conv = (char)chascii;
									String convstr = Character.toString(conv);
									us[j] = convstr;
								}
								System.out.print(us[j]+ " ");
								}
						 
						 System.out.println("");
						 System.out.println("End (round " + i + ")");
							
						 i += 1;
						 
						 // Check if the user has completed guessing the array 
						 if (Arrays.equals(u, guess))  {
							 check = 1;
						 }
					 
					 
				} // while 
				
				System.out.println("");
				System.out.println("Congratulatons! You took " + (i-1) + " rounds to complete the game.");
				
	}
			
}
